tidalmigrations/tidalmigrations.github.io

- _data/sidebars/main_sidebar.yml
- pages/user guides/tag_to_ip_addresses.md
Adds a guide to get all the IPs for all the servers, that are dependencies for any applications with a given tag.
> Add guide to get all IPs for apps with a tag

- pages/tidal tools/sourcecode.md
Adds a 'Tip' to the source code analysis guide.
> Add sample code reference to code analysis guide

- pages/tidal tools/discover.md
- pages/user guides/discovery_techniques.md
fixes two dead links that returned 404s.
The external one, switched to the RedHat docs for named.conf.
> Fix dead links

- _data/sidebars/main_sidebar.yml
- pages/tidal tools/general-troubleshooting.md
Adds page and includes suggestion on receiving emails with outlook.
> Adds a general troubleshooting page

- pages/tidal tools/analyze_database.md
Also adds `;` to other commands.
> Add additional grant statement for SQLServer

- _data/sidebars/main_sidebar.yml
- pages/user guides/exporting_move_groups_to_csv.md
- Adds the guide to the navigation menu
- Also adjusts a few words in the guide
> Adds the exporting server to the navigation menu

- pages/tidal tools/analyze.md
Use correct command syntax. No flag needed.
> Correct command

- pages/tidal tools/analyze.md
Adding troubleshooting section mentioning `--timeout` flag.
> Adding troubleshooting section

- pages/tidal tools/getstarted.md
- pages/tidal tools/troubleshooting.md
fix small typos found while reviewing the booklet
> fix typos 

- interviews.md
Adds a guide to cover the goals and best practices for completely application assessment interviews.
> Add initial interview best practices

- pages/api/authentication.md
- pages/api/importing_servers.md
This PR makes two small corrections:
- Correct ping endpoint path
- Correct example API command to be work with copy and pasting
> Small corrections

- pages/user guides/public_urls.md
Corrects the number, and uses headings intstead of a list, which wasn't working between MD parsing to HTML.
> Correct numbering

- pages/tidal tools/analyze_database.md
This PR introduces the following changes:
- Adds supported versions of MySQL and PostgreSQL to the supported versions table
- Adds sections on creating/configuring users for MySQL and PostgreSQL
- Improves typography and formatting
> Update guide with information on MySQL and Postgres

- oracle_cdb_user.sql
- oracle_user.sql
- pages/tidal tools/analyze_database.md
- Improve note style at top of doc
- Update Oracle user creation script
- Also adds the CDB user creation script needed for Oracle CDB database support.
Still pending for another PR is to document how to configure the YAML file to support CDB database access.
> Update Oracle user creation script

- mssql_user.sql
- pages/tidal tools/analyze_database.md
Updates the user creation script for SQLServer to complete a database analysis for it.
> Update SQLServer user creation script

- _data/sidebars/main_sidebar.yml
- pages/api/Using_with_postman.md
- pages/api/create_interview_questions.md
- pages/api/get_several.md
- pages/api/getting_started.md
- pages/api/importing_applications.md
- pages/api/importing_servers.md
- pages/tidal tools/analyze_database.md
- pages/user guides/export_ip_addresses.md
- pages/user guides/source_code_insights.md
This PR will resolve this issue - https://github.com/tidalmigrations/tidalmigrations.github.io/issues/82
Before merging this, need to confirm any external references to these older URLs are updated.
> Consistent link delimiters

- pages/tidal tools/sourcecode.md
Adds a tip to link to the command that can be used to run source code analysis on lots of applications.
> Add tip to link to command for creating directories

- pages/tidal tools/troubleshooting.md
This PR moves PostgreSQL troubleshooting subsection to General Troubleshooting section, where it belongs.
> Move section to General Troubleshooting

- _data/sidebars/main_sidebar.yml
Leaving here for when we're ready to release projects
> Add projects feature to sidebar

- pages/user guides/assessment_projects.md
Corrects a small typo reported by Peter
> Correct grammar in projects guide

- pages/tidal tools/analyze_database.md
Updates the supported database versions in the database analysis guide.
> Update supported database versions

- pages/tidal tools/machine_stats.md
This PR introduces the following changes:
1. Describes non-WinRM approach for Machine Stats for Windows
2. Adds the information about `-UserName` and `-ServersPath` parameters of Machine Stats for Windows
3. Adds section on Machine Stats for Hypervisors
> Update Machine Stats guides

- _includes/feedback.html
- _includes/footer.html
Adds a link to this repo to invite anyone to share their feedback or suggestions.
Adds the link to both the header and to the footer.
> Edit on GitHub

- pages/user guides/tidal-vms.md
This PR reverts the changes in #182 and some minor improvements. This is a WIP because I'm facing problems with OVFTool on Windows and cannot generate the OVA file.
TODO:
> Move back to OVA using Packer builder

- _data/sidebars/main_sidebar.yml
- pages/user guides/downloads.md
- pages/user guides/tidal-vms.md
This PR adds the following changes:
- Add pre-config VM in the download section
- Link offline guides to the pre-config VM guide
- Add pre-config VM to the side menu bar
> Link offline guides to Pre-configured VM

- pages/tidal tools/analyze_database.md
Fixes path to the settings page.
> Fix profile settings path on analyze database page

- pages/tidal tools/getstarted.md
- pages/tidal tools/vsphere.md
This PR adds Notes to communicate that we are encrypting Tidal Migrations and vSphere passwords.
> document Tidal and vsphere password encryption

- pages/tidal tools/analyze_database.md
- pages/tidal tools/getstarted.md
taking a pass at our Database analysis guide.
> improve database analysis documentation

- pages/tidal tools/machine_stats.md
Document the -NoWinRM flag, and some small updates to the MS4W intro.
> Added MS4W section on NoWinRM

- pages/tidal tools/machine_stats.md
Updated the MS4W guide to mirror the MS4U section.
Added detailed instructions for how to run MS4W in a scheduled task.
> Re-wrote the guide on how to run MS4W

- pages/tidal tools/machine_stats.md
- pages/user guides/tidal-vms.md
Some suggestions to consider to improve the clarity and readability of the VM appliance setup and requirements.
> Suggestions to improve clarity and conciseness 

- pages/user guides/importing_to_excel.md
Adds some details about useful information when importing from excel. Including link for a sample spreadsheet and which fields are required when importing.
> Add notes about sample and required data for excel import

- pages/tidal tools/machine_stats.md
- pages/user guides/integrating_with_azure_migrate.md
This PR documents the data points captured by azure migrate as well as machine stats. It aims to provide more clarity for users on what to expect.
> include datapoints captured by machine stats and azure migrate

- pages/tidal tools/machine_stats.md
The intent is to change the table of contents hierarchy to match the contents logical structure.
on `master`
with this PR
> Style titles to follow logical hierarchy

- pages/tidal tools/syncservers.md
- simplify wording
- include info about creation of custom fields and different behaviour
depending on command usage.
> Update sync docs

- pages/tidal tools/troubleshooting.md
Should resolve https://github.com/tidalmigrations/tidalmigrations.github.io/issues/70
> Adds troubleshooting steps for configuring docker on linux proxies

- pages/user guides/tidal-vms.md
Highlight the messaging about Windows Server not having all the tools/software as Ubuntu Server.
Updated the credentials.
> Update Windows Server image docs

- book/discover.md
- pages/user guides/importing_from_excel.md
Renames the `importing_to_excel` file to `importing_from_excel`.
> Rename import file and update its references

- pages/tidal tools/vsphere.md
- pages/user guides/tidal-vms.md
Adjusting the vSphere guide to document the new data points captured by Tidal Tools  [PR](https://github.com/tidalmigrations/tidal-tools/pull/21)
> adjust vsphere guide

- pages/tidal tools/machine_stats.md
This PR changes the XML file location. The new XML file also removes the `Duration` flag for the scheduled task based on Prem's review.
> Update schedule task XML file

- pages/tidal tools/syncservers.md
The current Application example is outdated and no longer compatible with the API. This PR fixes the issue.
> adjust syncservers documentation

- pages/tidal tools/vsphere.md
This PR adds basic troubleshooting details for vSphere services
> add vSphere troubleshooting docs

- pages/tidal tools/analyze_logs.md
Just some quick typos I noticed in the docs yesterday.  PTAL @ramizpolic
> Fit Typos: log -> logs; code -> logs in analyze_logs.md

- pages/user guides/importing_from_excel.md
- reference new behavior of sync
- remove references to virtualization clusters
> Update importer guides

- pages/tidal tools/sourcecode.md
- pages/user guides/code_analysis_overview.md
- Improved and simplified the existing usage guide on how to perform code analysis. Simplifying the content, and directions, while improving the clarity. Also improved the structure of the content.
- Adds an additional guide covering the compatibility and capabilities of the code analysis feature. Currently not added to the navigation but can be at any time.
> code analysis overview and usage improvements

- _data/sidebars/main_sidebar.yml
- pages/user guides/code_analysis_overview.md
- Improvements to the source code analysis overview page.
- Includes the overview page on the main menu navigation.
> Improve code overview and add to navigation
