- pages/tidal tools/analyze.md
- pages/tidal tools/aws.md
- pages/tidal tools/getstarted.md
- pages/user guides/discovery_techniques.md
This PR introduces some changes related to the recent rename of `tidal analyze` command to `tidal analyze web`.
Also some outdated information was corrected.
> Change `tidal analyze` to `tidal analyze web`

- pages/tidal tools/syncservers.md
There is no parameter `host_name` for applications. No need to include this in the example.
> Remove incorrect key from example app body data

- .vscode/settings.json
Removes dotfile editor config from the repo. Not needed and if it is, can be setup by people who need it and be set to ignore in .gitignore.
> Remove editor config

- pages/tidal tools/vsphere.md
Improves the content in the vSphere integration guide.
- Corrects some content and steps that were out of date.
- Adds more information for the needed inputs and values.
- Improves the wording on the existing content to make it easier to read and follow.
- Reorders some content, moving the 'other' configuration options to the end. They are optionl, not really need used by most people.
- Also improves the markdown spacing and formatting, no visible impact on render though.
> Improve vSphere integration guide

- _data/sidebars/main_sidebar.yml
This is ready for a review. Really small change.
It should be merged when the Tidal Tools listing is available to everyone on the GCP marketplace.
> Add GCP guide to navigation menu

- pages/tidal tools/analyze_database.md
A few improvements for the database analysis guide:
- Add new supported db version, Oracle 18c
- Add information about `analyze_workload` option
Doesn't impact rendered content:
- Remove redundant whitespace
> Updates for the database analysis guide

- _data/sidebars/main_sidebar.yml
Adds the public url and interview best practices guide to the side navigation menu.
> Add Public URL and Interview guides to navigation

- _data/sidebars/main_sidebar.yml
- pages/tidal tools/zone-export.md
This step is critical for customers using Windows DNS, in order to use `tidal discover`. Documenting it here so we can easily reference it during the process.
> Add guide on exporting zonefile from Windows Server

- pages/tidal tools/machine_stats.md
This PR introduces the following changes:
- Specify Python versions required from Ansible control node and managed nodes
- Correct the machine_stats invocation command line
> Update machine stats guide

- pages/tidal tools/syncservers.md
A small typo fix on the sync servers page.
> Fix typo on sync guide

- pages/tidal tools/syncservers.md
Includes the database instance in the sample application JSON object for the `tidal sync apps` command.
> Include database instances in sample app sync

- pages/tidal tools/analyze_database.md
- pages/tidal tools/troubleshooting.md
This PR adds the user permissions script section for PostgreSQL 10+ (based on the [upstream script](https://storage.googleapis.com/general-migvisor-public/postgresql_readonly_user.sql)) and the PostgreSQL troubleshooting section to be referred from `tidal analyze db`
> PostgreSQL user permissions script and troubleshooting

- pages/user guides/public_urls.md
Adds a note about breaking large CIDR ranges into smaller ones and references the subnet builder on tidalmigrations.com.
> Add note about large ranges

- pages/api/authentication.md
- pages/api/get_several.md
- pages/api/getting_started.md
- pages/api/importing_applications.md
- pages/api/importing_servers.md
Update from old login/client system to new workspaces
We need this to be able to host the signup app on get.tidalmg.com only.
> Switch references to get.tidalmg.com

- pages/user guides/integrating_with_servicenow.md
Now that the servicenow update set has been updated, we can re-add database support to the feature. This PR updates the guides accordingly, and also removes references to update set import errors, which have been resolved.
> Updated servicenow guide with databases

- pages/user guides/integrating_with_azure_migrate.md
I don't have an SSH key on my azure cloud shell, and don't need one to clone a public repo.
> switch to https:// endpoint for git

- pages/user guides/tidal-vms.md
Updated the download link for the preconfigured Ubuntu VM served from this page. It's now located in a new S3 bucket behind a cloudfront distribution.
> Update download location for preconfigured VM images

- _data/sidebars/main_sidebar.yml
- pages/tidal tools/tidal_offline.md
Updated tidal-offline.html with feedback gathered [here](https://docs.google.com/document/d/1f9L3SmIdojKbidGqhawPZUV9xXh2CUeE6kNANTotXbU/edit), and added this page to the main sidebar for release.
It's under `Introduction` in this PR. I initially assumed it should go under `Discovery`, but it contains information on processes outside the discovery phase (like source code analysis - which is `Assess`). This will also allow the page to grow and include any Tidal process which can be completed offline, rather than just discovery.  However this is just a thought - if you think it should go under `Discovery` instead please let me know.
> Update and release Tidal Offline

- pages/user guides/tidal-vms.md
A pass over the existing guides for Ubuntu 18.04 VM image since we have changed our approach from VMware as a builder to exporting OVA from the AWS EC2. This is also done to make the image available for public use.
> Update new OVA related information

- pages/tidal tools/machine_stats.md
- pages/tidal tools/tidal_offline.md
Split instructions for MS4U into the various approaches for gathering data, and explained the use cases for each.
These are:
- Manual single invocation
- Invoke and pipe to TMP in one command
- Gether data over time with cron
Also updated the MS4U section in the tidal offline docs, which previously had duplicate instructions for running machine stats. Now, this doc should link to the instructions in the machine stats page, rather than us having to maintain two versions.
> Improve machine stats for Unix documentation

- pages/tidal tools/machine_stats.md
- pages/user guides/tidal-vms.md
Added a recommended specs section to the guide for Machine Stats for Unix. This breaks down our specs into three bands, as suggested [here](https://tidalmg.slack.com/archives/C01LZV12W90/p1649434189150119).
Also added a note to the Ubuntu preconfigured VM linking to the recommended specs.
> Added MS4U limitations

- pages/tidal tools/machine_stats.md
Added a section to the MS4W guide on the limitations of the software.
Rather than compute power, MS4W is limited by scheduled job invocation period.
Also updated a link to powershell docs found in this section, which was broken.
> Added MS4W Limitations

- pages/tidal tools/machine_stats.md
Provided additional detail and an alternative option for working around the fact that MS4W is not digitally signed, and needing to change your execution policy.
> Clarify instructions around setting MS4W execution policy

- _data/sidebars/main_sidebar.yml
Currently the link in the main navigation returns a page not found error! This fixes that
> Fix navigation for vm guide

- pages/tidal tools/vsphere.md
@jmariomejiap for you to consider.
GB is the correct symbol for gigabyte. I think useful to state that the instanceuuid is the property from vsphere (vs say a unit, or assigned id from vsphere).
> Correct units

- pages/tidal tools/google.md
- pages/tidal tools/machine_stats.md
A couple of minor improvements:
- Add keywords to the Machine Stats page
- Fix a Tidal Tools title
> Fix a Tidal tools title and add machine stats keywords

- pages/tidal tools/machine_stats.md
CPU utilization gathering is not currently intended for public use. The guide includes an off-hand reference to it as a use case. This PR removes that to eliminate confusion.
> Removed out-of-context reference to CPU utilization gathering

- pages/user guides/tidal-vms.md
The Windows and Ubuntu OVAs use VMDK as the disk file type. This is causing import issues on the VDI-based virtualization software such as VirtualBox. Thus, this PR explicitly mentions the VMDK file type as the supported `import image type` for the virtual environment software.
> Add VMDK file type to supported vir env softwares

- pages/user guides/financial_impact.md
> Updated financial classification definitions with examples
